### ISSUE TITLE
NeRV: Neural Reflectance and Visibility Fields for Relighting and View Synthesis

### ISSUE THREAD

**Issue by cfoster0** [yenchenlin/awesome-NeRF#11]
https://arxiv.org/abs/2012.03927

https://people.eecs.berkeley.edu/~pratul/nerv/

**Comment by yenchenlin** [comment]
Do you want to submit a pull request?

**Comment by cfoster0** [comment]
Not at my machine right now, but I can later if you want.

**Comment by yenchenlin** [comment]
yeah please, thank you!

**Comment by cfoster0** [comment]
NeRD also came out today, with a similar concept. 

https://arxiv.org/abs/2012.03918

https://markboss.me/publication/2021-nerd/

Do you want me to include it in the PR?
