### ISSUE TITLE
And maybe also a talk from Matthias Niessner

### ISSUE THREAD

**Issue by yunlu-chen** [yenchenlin/awesome-NeRF#16]
https://www.youtube.com/watch?v=zNvS5hQsWEo&list=PLkcK4tsjESpT3PWVo62UudYMZmU1D9b0j

**Comment by yenchenlin** [comment]
Thanks for the suggestion! However, I will probably skip this one because only the latter part is about NeRF and it's about dynamic NeRFs, a subfield that's changing too fast for this README to handle.
