### ISSUE TITLE
Why is NeRF very slow at test time and how to make it faster ? 

### ISSUE THREAD

**Issue by Jiakui** [yenchenlin/awesome-NeRF#23]
I heard that NeRF is very slow at test time, "Rendering a single 1280x720 image on one such GPU takes ∼30 seconds at test time ". 

Can we just generate low resolution images and then use some super resolution method to improve the resolution ? That may make it faster.

**Comment by yenchenlin** [comment]
Hello @Jiakui , in my opinion, the biggest benefit of NeRF's rendering process is the guarantee of multi-view consistency. Applying a super-resolution algorithm on top of each image separately will lose that potentially.

**Comment by Jiakui** [comment]
OK, can you briefly explain why NeRF runs very slowly at inferece stage ?   Is it due to the MLP layers computation cost too high, or the volume rendering stage very slow ?  Thanks!

**Comment by kwea123** [comment]
These two are all reasons, but I think the volume rendering part is more problematic. For a 400x400 image, it samples 64 coarse samples and 64+128 fine samples, which makes 400x400x(64+64+128) = 40960000 samples to do MLP inference.
To accelerate this, you can for example try [NSVF](https://github.com/facebookresearch/NSVF) that uses a special data structure to accelerate.
